Admin/Controllers/AdminController.cs
using System;
using System.Text;
using Admin.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;


namespace Admin.Controllers
{
    public class AdminController : Controller
    {
        // Returns the customer information in a tabular format
        public async Task<IActionResult> Index()
        {
            var response = await NWBAWebAPI.InitializeClient().GetAsync("api/customer");

            if (!response.IsSuccessStatusCode)
                throw new Exception();

            // Storing the response details recieved from web api.
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response recieved from web api and storing into a list.
            var customers = JsonConvert.DeserializeObject<List<CustomerDto>>(result);

            return View(customers);
        }


        // Returns the list of transactions in a tabular format
        [ActionName("ViewTransaction")]
        public async Task<IActionResult> ViewTransactions()
        {
            var response = await NWBAWebAPI.InitializeClient().GetAsync("api/transaction");

            if (!response.IsSuccessStatusCode)
                throw new Exception();

            // Storing the response details recieved from web api.
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response recieved from web api and storing into a list.
            var transaction = JsonConvert.DeserializeObject<List<TransactionDto>>(result);

            return View(transaction);
        }


        // Returns the login status of customers
        [ActionName("CheckLogin")]
        public async Task<IActionResult> CheckLogin()
        {
            if (!HttpContext.Session.GetInt32("admin").HasValue)
                return RedirectToAction("Index", "Home");

            var loginAPI = await NWBAWebAPI.InitializeClient().GetAsync("api/login");
            string loginstr = loginAPI.Content.ReadAsStringAsync().Result;
            List<LoginDto> logins = JsonConvert.DeserializeObject<List<LoginDto>>(loginstr);
            return View(logins);
        }


        // Displays the UI for editing the customer profile
        // GET: Customer/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var response = await NWBAWebAPI.InitializeClient().GetAsync($"api/customer/{id}");

            if (!response.IsSuccessStatusCode)
                throw new Exception();

            var result = response.Content.ReadAsStringAsync().Result;
            var customer = JsonConvert.DeserializeObject<CustomerDto>(result);

            return View(customer);
        }

        // POST: Customer/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CustomerDto customer)
        {
            if (id != customer.CustomerID)
                return NotFound();

            if (ModelState.IsValid)
            {
                var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");
                var response = NWBAWebAPI.InitializeClient().PutAsync("api/customer", content).Result;

                if (response.IsSuccessStatusCode)
                    return RedirectToAction("Index");
            }

            return View(customer);
        }


        // Returns all the scheduled bill payments
        [ActionName("CheckBillPay")]
        public async Task<IActionResult> CheckBillPay()
        {
            if (!HttpContext.Session.GetInt32("admin").HasValue)
                return RedirectToAction("Index", "Home");
            var billPayAPI = await NWBAWebAPI.InitializeClient().GetAsync("api/billpay");
            if (!billPayAPI.IsSuccessStatusCode)
                throw new Exception();
            string billPaystr = billPayAPI.Content.ReadAsStringAsync().Result;

            List<BillPayDto> billPays = JsonConvert.DeserializeObject<List<BillPayDto>>(billPaystr);
            return View(billPays);
        }


        // Option to toggle between blocking and unblocking the scheduled payments
        [HttpPost,ActionName("CheckBillPay")]
        public async Task<IActionResult> ActiveChange(int id)
        {
            if (!HttpContext.Session.GetInt32("admin").HasValue)
                return RedirectToAction("Index", "Home");
            var billPayAPI = await NWBAWebAPI.InitializeClient().GetAsync("api/billpay");
            if (!billPayAPI.IsSuccessStatusCode)
                throw new Exception();
            string billPaystr = billPayAPI.Content.ReadAsStringAsync().Result;
            List<BillPayDto> billPays = JsonConvert.DeserializeObject<List<BillPayDto>>(billPaystr);
            BillPayDto billPay = billPays.Find(n => n.BillPayId.Equals(id));
            if (billPay.Active)
                billPay.Active= false;
            else
                billPay.Active = true;
            var result =  await NWBAWebAPI.InitializeClient().PutAsJsonAsync("api/billpay", billPay);
            return RedirectToAction(nameof(CheckBillPay));
        }


        // Lock the user account
        [ActionName("blocklogin"),HttpPost]
        public async Task<IActionResult> ManualLockdown(String id)
        {
            if (!HttpContext.Session.GetInt32("admin").HasValue)
                return RedirectToAction("Index", "Home");
            var loginAPI = await NWBAWebAPI.InitializeClient().GetAsync("api/login");
            string loginstr = loginAPI.Content.ReadAsStringAsync().Result;
            List<LoginDto> logins = JsonConvert.DeserializeObject<List<LoginDto>>(loginstr);
            LoginDto login = logins.Find(n => n.UserID.Equals(id));

            if (DateTime.Compare(login.Timer, DateTime.UtcNow) > 0)
                login.Timer = DateTime.UtcNow;
            else
                login.Timer = DateTime.UtcNow.AddMinutes(1);

            await NWBAWebAPI.InitializeClient().PutAsJsonAsync("api/login", login);
            return RedirectToAction(nameof(CheckLogin));
        }
    }
}

Admin/Controllers/ChartController.cs
using System.Collections.Generic;
using System.Linq;
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Admin.Controllers
{
    public class ChartController : Controller
    {
        // Linq query to fetch the data from the transaction table
        public async System.Threading.Tasks.Task<IActionResult> Data()
        {
            var transactionAPI = await NWBAWebAPI.InitializeClient().GetAsync("api/transaction");
            string transactionrstr = transactionAPI.Content.ReadAsStringAsync().Result;
            List<TransactionDto> transactions = JsonConvert.DeserializeObject<List<TransactionDto>>(transactionrstr);
            var result = transactions
                           .GroupBy(x => new { group = x.AccountNumber })
                           .Select(group => new
                           {
                               AccountNumber = group.Key.group,
                               count = group.Count()
                           }
                          ).OrderByDescending(o => o.count).ToList();

            var labels = result.Select(x => x.AccountNumber).ToArray();
            var values = result.Select(x => x.count).ToArray();

            List<object> list1 = new List<object>
            {
                labels,
                values
            };

            return Json(list1);
        }
        public IActionResult Index()
        {
            return View("Index");
        }
    }
}

Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @{
                            var isLoggedIn = Context.Session.GetInt32("admin").HasValue;
                        }
                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">
                                    Welcome, Admin
                                </span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="CheckBillPay">BPay</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Chart" asp-action="Index">Charts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="ViewTransaction">View Statements</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="CheckLogin">Manage Customer Credentials</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>